version: '3.9'
services:
  web:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env

    ports:
      - '5455:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:

